[font.normal]
family = "Terminus"
style = "Regular"

[window.padding]
x = 32
y = 32

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#1c1c1c"
foreground = "#dfdfaf"
